server:
  port: 8086

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/aws?serverTimezone=UTC
    username: root
    password: qaz923923
  flyway:
    url: jdbc:mysql://localhost:3306/aws?serverTimezone=UTC
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    locations: db/migration
  cloud:
    aws:
      credentials:
        access-key: AKIAVRUVRQESBKFN5B6Y
        secret-key: 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
s3:
  bucket:
    name: com.vladkostromin.s3app.bucket
    region: eu-central-1
jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keyLength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: vladkostrov


